=== igormlshkv/hihwai/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

<xs:element name="hipertext" type="hipertextType"/>  

<xs:complexType name="hipertextType">
		<xs:sequence>
			<xs:element name="author" type="authorType" ></xs:element>
            <xs:element name="pilkarze" type="pilkarzeType" maxOccurs="unbounded"> </xs:element>
            <xs:element name="artykuly" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="artykul" maxOccurs="unbounded">
                        <xs:complexType>
                        <xs:sequence>
                        <xs:element name="title" type="shortstringType"></xs:element>
                        <xs:element name="content" type="xs:string" maxOccurs="unbounded"></xs:element>
                    </xs:sequence>
                     </xs:complexType>


                    </xs:element>
                    
                 </xs:sequence>
                </xs:complexType>
            </xs:element>
            


           
		</xs:sequence>
	</xs:complexType>

<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />		
			<xs:element name="lastname" type="xs:string" />
		</xs:sequence>
</xs:complexType>

<xs:complexType name="pilkarzeType">
		<xs:sequence>
            <xs:element name="pilkarz" type="pilkarzType" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
</xs:complexType>

<xs:complexType name="pilkarzType">
    <xs:sequence>
        <xs:element name="name" type="nameString" minOccurs="1" maxOccurs="1"></xs:element>
        <xs:element name="birthday" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
        <xs:element name="death" type="xs:date" minOccurs="0" maxOccurs="1"></xs:element> 
        <xs:element name="nationality" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
        <xs:element name="description" type="xs:string" minOccurs="1"></xs:element>
        <xs:element name="image" type="imgType" minOccurs="0"></xs:element>
        <xs:element name="achievements" type="achievementsType" minOccurs="1" maxOccurs="1"></xs:element>

    </xs:sequence>
    <xs:attribute name="alive"></xs:attribute>
    <xs:attribute name="retired"></xs:attribute>

</xs:complexType>

<xs:complexType name="imgType">
    <xs:sequence>
        <xs:element name="link">
            <xs:complexType>
                <xs:attribute name="source" type="xs:string"></xs:attribute>
            </xs:complexType>            
        </xs:element>
        <xs:element name="imgdescription" type="xs:string"></xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="achievementsType">
    <xs:sequence>
        <xs:element name="achievement" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="name" type="xs:string"></xs:element>
                    <xs:element name="date" type="xs:gYear" minOccurs="0" maxOccurs="unbounded"></xs:element>
                </xs:sequence>
            </xs:complexType>


        </xs:element>
    </xs:sequence>




</xs:complexType>

<xs:attribute name="alive">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="retired">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:simpleType name="nameString">
    <xs:restriction base="xs:string">
        <xs:minLength value="3"></xs:minLength>
        <xs:maxLength value="30"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="shortstringType">
    <xs:restriction base="xs:string">
        <xs:minLength value="1"></xs:minLength>
        <xs:maxLength value="35"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

<xs:attribute name="lang" type="xs:string" default="pl-PL"/>
</xs:schema>

=== igormlshkv/hihwai/index.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="index.xsd">

    <author>
        <name>Igor</name>
        <lastname>Maliszkiewicz</lastname>
    </author>


    <pilkarze>
        <pilkarz alive="no" retired="yes">
            <name>Diego Armando Maradona</name>
            <birthday>1960-10-30</birthday>
            <death>2020-11-25</death>
            <nationality>Argentyna</nationality>
            <description>Diego Armando Maradona urodził się 30 października 1960 roku w Lanus na przedmieściach Buenos Aires. W piłkę zaczął grać, gdy miał 9 lat. Zapisał się wtedy do młodzieżowego zespołu Cebbolitates, który był odłamem Argentinos Jrs. Dzięki swojemu talentowi został nazwany Pibe de Oro (Złoty Chłopiec).
                Po sześciu latach gry w swoim klubie został przeniesiony do podstawowego składu Argentinos Juniors. Cztery miesiące później Diego zagrał swój pierwszy mecz w kadrze narodowej U-16. W 1978 roku nie został powołany przez trenera pierwszej reprezentacji Argentyny - Manottiego - na mistrzostwa świata, gdyż trener uważał, że Maradona jest jeszcze zbyt młody. Zawiedziony, wziął się ostro za treningi, aby w końcu go dostrzeżono. W niedługim czasie okrzyknięto go następcą Pele. W 1981 roku trafił do jednego z najlepszych argentyńskich klubów - Boca Juniors, za sumę miliona funtów. W 1982 roku dostał szansę i pojechał na mistrzostwa świata w Hiszpanii. Na początku grał całkiem dobrze, strzelił 2 bramki. Kryzys przyszedł w meczach z Włochami i Brazylią, grał fatalnie, popełniał wiele błędów, w meczu z Canarinhos dostał czerwoną kartkę. Argentyna odpadła w drugiej rundzie turnieju.
                W tym samym roku Diego Maradona przeszedł do FC Barcelony za sumę 3 milionów funtów, co jak na tamte czasu było absolutnym rekordem. Mimo, że nie grał za wiele, w pierwszym sezonie strzelił 26 bramek, zdobył z Blaugraną mistrzostwo Hiszpanii, Copa del Rey i Superpuchar Hiszpanii. Gdy trenerem Barçy został Menotti, Maradona grał dużo więcej i dużo skuteczniej. Był maszyną nie do zatrzymania. Niestety, w meczu z Athletic Bilbao, Diego złamał nogę, co wykluczyło go z gry na trzy miesiące.
                Po wyleczeniu kontuzji postanowił opuścić klub i za sumę 7 milionów funtów trafił do Napoli. Wraz z Napoli zdobył w 1987 roku mistrzostwo i puchar kraju. Rok wcześniej na mistrzostwach świata, był czołową postacią reprezentacji Argentyny. Strzelił pięć bramek, z czego najbardziej znana to ta, strzelona ręką w meczy z Anglia. Kolejnym sukcesem w karierze Maradony było zdobycie z Napoli Pucharu UEFA w 1989 roku. Na mistrzostwach świata w 1990r. ponownie poprowadził Argentynę do finału, i ponownie zmierzył się z Niemcami. Ty razem Europejczycy okazali się zbyt trudnymi przeciwnikami. Po tej imprezie zaczęły się problemy Diego. Został on przyłapany na dopingu, za co został zdyskwalifikowany na 15 miesięcy.
                W 1992 roku, opuścił Włochy i przeniósł się do Sevilli CF, gdzie grał niespełna rok. Później trafił do Newell's Old Boys, jednak przygoda z tym klubem zakończyła się szybciej niż z Sevillą.
                "Jeśli rodzice nas szukali, wiedzieli, gdzie nas znaleźć. Zawsze tam się uganialiśmy za piłką. (…) Po prawej był pokój rodziców, po lewej – nie więcej niż dwa metry na dwa – pokój dzieci… Ośmiorga dzieci. Kiedy padał deszcz, trzeba było omijać miejsca, gdzie kapała woda, bo bardziej mogłeś zmoknąć w środku niż na zewnątrz. Dobra, nie chodzi o to, że nie mieliśmy łazienki – nie mieliśmy wody, ja zacząłem ją nosić w dwudziestolitrowych puszkach po oleju (…)."
                Jego losy ściśle wpisują się w historię Argentyny. To postać tragiczna. Historia Argentyny to też wzloty i upadki. Diego od najmłodszych lat był symbolem, stał się celebrytą wbrew pochodzeniu, ubóstwu. Nie potrafił sobie z tym poradzić. A jego sława dawała nadzieję gorzej sytuowanym Argentyńczykom. Potrzebowali takiego idola, który inspiruje i jednocześnie ma rysy na wizerunku. Maradona podziwiał lewicowych przywódców, bo znał biedę. Podziw dla populistów w Ameryce Łacińskiej to swoiste wezwanie do zainteresowania się nizinami społecznymi. To część jego legendy.
                Maradona był piłkarskim geniuszem, który na pewnym momencie kariery pobłądził. Z pewnością w historii futbolu nigdy nie było zawodnika, który przez tyle lat grał na tak wysokim poziomie i jednocześnie prowadził tak niesportowy tryb życia. Był uzależniony od kokainy. Jak sam później przyznał, w Neapolu „narkotyki były wszędzie, praktycznie podawano mi je na tacy”. Spektakularny upadek nastąpił 17 marca 1991 roku, kiedy po meczu Napoli-Bari w próbce moczu piłkarza wykryto obecność narkotyku. To był ostatni mecz Argentyńczyka w błękitnej koszulce. Kara – 15 miesięcy zawieszenia. W tym samym roku trzydziestolatek został zatrzymany przez policję w rodzinnym mieście. Posiadał przy sobie znaczne ilości kokainy. Mimo że uniknął więzienia, jego życie nigdy już nie wróciło na właściwe tory.
            </description>
            <image>
                <link source="img/maradona.png"></link>
                <imgdescription>Zdjęcie Diego Maradony</imgdescription>
            </image>
            <achievements>
                <achievement>
                    <name>Mistrz</name>
                    <date>1986</date>
            </achievement>
                <achievement>
                    <name>Wicemistrz Świata</name>
                    <date>1990 </date>
                </achievement>
                <achievement>
                    <name>Mistrzostwo Argentyny</name>
                    <date>1981</date>
                </achievement>
                <achievement>
                    <name>Puchar Króla, Puchar Ligi Hiszpańskiej i Super Puchar Hiszpanii</name>
                    <date>1983</date>
                </achievement>
                <achievement><name>Mistrzostwo Włoch</name>
                    <date>1987</date>
                    <date>1990</date>
                 </achievement>
                <achievement>
                    <name>Zdobywca Pucharu UEFA</name>
                    <date>1989</date>
                </achievement>
                <achievement>
                    <name>Król strzelców Ligi Argentyńskiej</name>
                    <date>1979</date>
                    <date>1980</date>
                    <date>1981</date> 
                </achievement>
                <achievement>
                    <name>Król strzelców Serii A</name>
                    <date>1988</date> 
                </achievement>
                <achievement>
                    <name>Najlepszy Piłkarz Świata według World Soccer Magazine</name>
                <date>1986</date>
                </achievement>
                <achievement>
                    <name>Złota Piłka France Football za całokształt</name>
                </achievement>
                <achievement>
                    <name>Złota Piłka dla najlepszego piłkarza MŚ</name>
                    <date>1986</date>
                </achievement>
                <achievement>
                    <name>Najlepszy piłkarz wszech czasów według głosowania internautów zorganizowanym przez FIFA</name>
                </achievement>
                <achievement>
                    <name>5-krotnie wybierany najlepszych piłkarzem Argentyny i Ameryki Południowej</name>
                </achievement>
            </achievements>

        </pilkarz>






        <pilkarz alive="yes" retired="yes">
            <name>Ronaldo de Asiss Moreira</name>
            <birthday>1980-03-21</birthday>
            <nationality>Brazylia</nationality>
            <description>
                Ronaldo de Asiss Moreira przyszedł na świat 21 marca 1980 roku w Porto Alegre. Swoją przygodę z piłką rozpoczął już w wieku 6 lat grając w lokalnym klubie. Wychowywał się w Porto Alegre wraz ze swoją matką, bratem i ojcem Joao, którego 'El Crack Total' nie pamięta dobrze, ponieważ gdy miał 12 lat, tata utopił się... w basenie. Od tego czasu "Mały Ronaldo" przywiązał się do matki Miqueliny, natomiast głową rodziny stał się starszy brat Roberto.
                Gdy Ronaldinho skończył 17 lat podpisał profesjonalny kontrakt z Gremio. W debiutanckim sezonie zagrał w 47 meczach strzelając 7 bramek, ale to był dopiero początek. Rok później zaliczył już 22 trafienia, a w 2000 roku w 43 spotkaniach aż 39 razy wpisywał się na listę strzelców. Do osiągnięć tego okresu należą mistrzostwo i puchar stanu Rio Grande do Sul.
                Młody Brazylijczyk swój pierwszy sukces odniósł na Mistrzostwach Świata U-17 w Egipcie. Turniej był dla niego szalenie udany, ponieważ poprowadził "Kanarków" do zwycięstwa w turnieju, a sam został królem strzelców. Po całym zdarzeniu oczywiście jego wybrano najlepszym zawodnikiem imprezy. 
                Dwa lata po MŚ "siedemnastek" nadszedł czas na debiut w seniorskiej ekipie Brazylii. Roni został powołany na towarzyski mecz z Łotwą (3-0). W meczu z Łotyszami zaprezentował dobry futbol, co zaowocowało powołaniem go przez selekcjonera Wanderley'a Luxemburga na Copa America w Paragwaju. "El Crack Total" zagrał w 4 spotkaniach strzelając przepiękną bramkę Wenezuelczykom. Do końca tamtego roku Gaucho rozegrał 20 spotkań w żółtym trykocie i strzelił 8 goli.
